import Head from "next/head";
import { useState } from "react";
import styles from "./index.module.css";

var amogus = null

export default function Home() {
  const [animalInput, setAnimalInput] = useState("");
  const [result, setResult] = useState();




        let SpeechRecognition = window.webkitSpeechRecognition || window.SpeechRecognition
        let SpeechGrammarList = window.SpeechGrammarList || window.webkitSpeechGrammarList

        var grammar = '#JSGF V1.0;'

        var recognition = new SpeechRecognition();
        var speechRecognitionList = new SpeechGrammarList();
        speechRecognitionList.addFromString(grammar, 1);
        recognition.grammars = speechRecognitionList;
        recognition.lang = 'en-US';
        recognition.interimResults = false;
        recognition.continuous = false;
        recognition.maxAlternatives = 1;

  async function onSubmit(event) {
    recognition.start()
  }
  
  async function geta(thing) {

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ animal: thing }),
      });
      await console.log(thing)
      const data = await response.json();
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`);
        return false
      }

      setResult(data.result);
      console.log(data.result)
      var msg = new SpeechSynthesisUtterance();
      msg.text = data.result
      window.speechSynthesis.speak(msg);
      setAnimalInput("");
      return false
    } catch(error) {
      console.error(error);
      alert(error.message);
      return false
    }
    return false
  }

  return (
    <div>
      <script>
          
      </script>
      <Head>
        <title>OpenAI Quickstart</title>
        <link rel="icon" href="/dog.png" />
      </Head>

      <main className={styles.main}>
        <img src="/dog.png" className={styles.icon} />
        <h3>VoiceGPT</h3>
        <form onSubmit={onSubmit}>
          <input
            type="text"
            name="animal"
            placeholder="Say anything"
            value={animalInput}
            onChange={(e) => setAnimalInput(e.target.value)}
          />
          <input id="click_to_record" type="submit" value="Send" />
        </form>
        <div className={styles.result}>{result}</div>
      
<div style={{
  position: "fixed",
  textAlign: "center",
  left: "0",
  bottom: "0",
}}>

  <p>I do NOT control and am not responsible for the responses generated by VoiceGPT. This application uses the OpenAI API. Made with ❤ by perko#6901</p>
  </div>
      </main>
      

    </div>
    
  );
}
